### ISSUE TITLE
Missing snappy-c  crashes pip installation.

### ISSUE THREAD

**Issue by dersmon** [syncrypt/client#1]
Never wrote my own package, so I am not quite sure if this is even a problem you can address: The PyPI installation crashed because I was missing the snappy-c libraries. Running `sudo apt-get install libsnappy-dev` solved the issue...

[pip.log.txt](https://github.com/syncrypt/client/files/344084/pip.log.txt)

**Comment by lordi** [comment]
Yea, you are right, not much can be done about that from our side. I think the [python-snappy](https://github.com/andrix/python-snappy) PyPI package should throw an error instead of crashing.

I will add a paragraph to the README so that future users won't stumble over the same issue.
Thanks!
