### ISSUE TITLE
Uncaught exception when attempting to initialize vault

### ISSUE THREAD

**Issue by zebbo** [syncrypt/client#3]
Running 
Syncrypt v0.1.4 
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4) 
Python 3.4.3

Two issues:
1) I used the credentials I signed up with before, so the authentication shouldn't fail
2) Probably if authentication fails, the exception should be caught somewhere

> xxx@xxx:~/syncript_test$ /usr/local/bin/syncrypt init
> INFO:syncrypt.app.syncrypt:Initializing <Vault: .>
> Email for storage.syncrypt.space: xxx@xxx.com
> Password: 
> ERROR:syncrypt.backends.binary:Invalid auth
> Traceback (most recent call last):
>   File "/usr/local/bin/syncrypt", line 266, in <module>
>     c.run()
>   File "/usr/local/bin/syncrypt", line 168, in run
>     self.loop.run_until_complete(self.app.init())
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
>     raise self._exception
>   File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
>     result = next(coro)
>   File "/usr/local/lib/python3.4/dist-packages/syncrypt/app/syncrypt.py", line 110, in init
>     yield from vault.backend.upload_identity(self.identity)
>   File "/usr/local/lib/python3.4/dist-packages/syncrypt/backends/binary.py", line 647, in myco
>     with (yield from self.manager.acquire_connection()) as conn:
>   File "/usr/local/lib/python3.4/dist-packages/syncrypt/backends/binary.py", line 540, in acquire_connection
>     yield from conn.connect()
>   File "/usr/local/lib/python3.4/dist-packages/syncrypt/backends/binary.py", line 165, in connect
>     raise StorageBackendInvalidAuth(response)
> syncrypt.backends.base.StorageBackendInvalidAuth: (Atom('error'), (Atom('login_failed'), b'xxx@xxx.com'))

**Comment by lordi** [comment]
Thanks I'll investigate. Are you positive that you didn't make a typo/mistake entering the credentials?

**Comment by zebbo** [comment]
Hi, well, I tried several times, then I changed my password in the Web UI and tried again. I also double-checked the credentials logging into the Web interface, but I'll try again today in the evening. Maybe it takes some time to sync the credentials??

**Comment by zebbo** [comment]
Tried again, but without success. Login via https://alpha.syncrypt.space/login is now failing, too. I tried to reuse the Sign up link from the mail to overwrite my account, but it just gave me an empty page after submitting my login data.

**Comment by bakkdoor** [comment]
Can you try setting up your account again? I've deleted your account so you should be able to recreate it with the alpha invitation link.

**Comment by zebbo** [comment]
Thanks, works like a charm now. Seems that my account somehow had got messed up. Curious to play around with it! Thanks again!

**Comment by lordi** [comment]
I'll reopen the issue because 2) hasn't been resolved.

**Comment by zebbo** [comment]
Sure, please let me know when you need further debug information.
