### ISSUE TITLE
Add reliable API for restarting & shutting down the daemon

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#34]
Related to syncrypt/elm-desktop#11

The current api endpoints don't seem to work correctly. We need a way to reliably start, stop and restart the daemon process from the desktop client (via system tray menu)

**Comment by lordi** [comment]
Can't verify here, shuts down and restarts fine. Any more info on the bug?

**Comment by bakkdoor** [comment]
I think we just need to hook this up correctly in the desktop code. Closing this.
