### ISSUE TITLE
Allow cloning a vault into a previously cloned location

### ISSUE THREAD

**Issue by lordi** [syncrypt/client#36]
Currently, it aborts with an exception because the folder is not empty.

If the vault ids match, we should just treat this the same way as if the user added the folder for syncing.

**Comment by bakkdoor** [comment]
Should we then just show an error message to the user and let them have to delete the `.vault` dir manually or should we do this for them and/or warn the user and delete the .vault folder if the vault ID inside `.vault/config` is invalid (due to the vault having been deleted on the server)

**Comment by lordi** [comment]
You are referring to the case where the vault ids do not match?

**Comment by bakkdoor** [comment]
Sorry I think I misread this initially, ignore my comment.

**Comment by lordi** [comment]
Works now
