### ISSUE TITLE
Newly created vault state is set to "failure"

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#38]
When creating a new vault, the daemon returns `state: "failure"` after cloning when hitting the `/v1/vault` API endpoint. This happens even when the vault creation worked and there was no error. 

This is only fixed by restarting the daemon. After a restart, it now returns `state: "ready"`.

**Comment by lordi** [comment]
Can't reproduce. Anything specific to the vault? Does it has an old .vault directory?

**Comment by bakkdoor** [comment]
This was a folder that was another vault before, but that was deleted. So the old .vault folder was deleted by the daemon before I used it for a new vault.

On April 3, 2018 8:26:28 AM GMT+02:00, "Hannes Gräuler" <notifications@github.com> wrote:
>Can't reproduce. Anything specific to the vault? Does it has an old
>.vault directory?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncrypt/client/issues/38#issuecomment-378141893

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
