### ISSUE TITLE
Duplicate vault possible?

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#40]
How do we want to deal with duplicate vaults? Right now, when the user wants to create a new vault with a folder that is already used for an existing & currently synchronized vault, the following happens:

* The vault gets added again and shows up twice, with the same remote vault ID
* Removing the newly added duplicate from sync in the admin panel removes only the duplicate vault
* After restarting the daemon, both entries for the removed vault are now gone from the vault list.

It seems like there's a different state in the daemon before and after restarting it with regard to these duplicate vaults.
I think the daemon should either still show the original vault card even after restarting in this scenario, *or* it should cause some kind of error (in daemon & GUI) that it's not possible to use the folder of another currently synced vault for a "new" vault.

**Comment by lordi** [comment]
Related to #36.

I think my proposal would be this simple rule: A remote vault can be cloned multiple times (i.e. on two hard drives), but a local folder can only be added once.

**Comment by bakkdoor** [comment]
👍 Sounds good to me, if you want to implement that behavior accordingly that would be great. So in the case I mentioned, the daemon would reply with an error and the GUI would display some error message that you can't add the same folder path twice as a vault folder.

**Comment by lordi** [comment]
Closing this, please reopen if it doesn't work in latest master. Proper error messages will be done in another issue.
