### ISSUE TITLE
ignore subfolder

### ISSUE THREAD

**Issue by jotech** [syncrypt/client#9]
I want to create a vault containing a subfolder which has files that shouldn't be synchronized.
Therefore I'm wondering whether there is something like a `.gitignore` in syncrypt?

**Comment by bakkdoor** [comment]
Yes, inside your vault config file (`.vault/config` in your vault directory) there's a `ignore` option. If you add your subfolder name (ignore patterns are separated by comma) to it. All files inside it will be ignored:

```
ignore = .*,subfolder
```

This will ignore all files beginning with `.` and all files in `subfolder`.
Let me know if that works for you.

**Comment by jotech** [comment]
perfect it's working, thanks a lot ;o)
